### ISSUE TITLE
Thanks and a couple of suggestions

### ISSUE THREAD

**Issue by eteitelbaum** [christopherkenny/apsr#1]
Thanks for this and your other awesome journal templates. I did not think we would have so many Quarto template options available for political science journals this quickly. Very exciting! 

I just wanted suggest a couple of things for the documentation. First, I was pleasantly surprised to find that the template plays nicely with ggplot and popular table packages that tend to be more html oriented like `kableExtra` and `gt`. I think it might be worth including examples of how to incorporate these into your apsr.qmd file since the whole idea behind Quarto is that you can easily integrate your R code and visualizations with your text.

```{r}
#| label: ggplot_figure
#| fig-cap: My ggplot Scatterplot
#| echo: false
#| message: false

library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

![ggplot_test](https://github.com/christopherkenny/apsr/assets/62634082/e4e0089b-6635-4962-b505-366bc0eb341a)

```{r}
#| label: my_gt_table
#| tbl-cap: "My gt Table"
#| echo: false
#| message: false

library(gt)

head(mtcars) |> gt()
```

![gt_test](https://github.com/christopherkenny/apsr/assets/62634082/1b44c6f7-7494-4abb-a29e-f24cf9d59661)

Also, I found the readme to be slightly confusing wrt the `classoption` parameter. It seems like the arguments for `classoption` are `twocolumn`, `singlespace`, `doublespace` and `onehalfspace` but the bullet points make it look like blind/nonblind and citation style might also be subsumed under `classoption`. 

Thanks again!

**Comment by christopherkenny** [comment]
Thank you. Some additions:

- The example document now explicitly demos using `ggplot2`.
- The example document now shows using `kableExtra`
- I've updated the readme to be a bit more verbose re classoptions.

Let me know if you think this fixes your concerns.

**Comment by eteitelbaum** [comment]
Looks really good. Thanks for making those updates. I wonder if you might want to set `echo` to false for the Figure 3 ggplot code chunk since it is running off the page, but I guess it does show the user how you can mix code with text? Probably a matter of taste.

**Comment by christopherkenny** [comment]
Fair point, it's a little bit of a mix between showing and telling for templates like this. Added a default echo: false for the document, since the template is probably sufficient to show what to do.
