### ISSUE TITLE
Bolding and justificaiton of title

### ISSUE THREAD

**Issue by eteitelbaum** [christopherkenny/apsr#2]
Not a huge deal, but wanted to note that the bolding and justification of the title in your template looks slightly different than the original Overleaf template. 

Here is the pdf produced by the original Overleaf template: 

![overleaf_template](https://github.com/christopherkenny/apsr/assets/62634082/b7d2ab8c-a578-4fee-b547-abf90886faa4)

Here is the one I rendered using your template: 

![kenny_template](https://github.com/christopherkenny/apsr/assets/62634082/fb229de9-10c8-48a2-82db-6b1b403f6a09)

Also can't seem to get the italics around APSR as in the original with: 

`title: American Political Science Review \emph{(APSR)} Submission Template`

Finally, I am noticing here that you are using the level 2 header in your apsr.qmd tutorial but level 1 headers are going to look more like the original...

**Comment by christopherkenny** [comment]
Thanks for pointing this out. Now using `pdflatex` to build it, which appears to fix the issue. I've also fixed the header levels, thanks!
